[setting]
avatar_proxyz="https://fdn.geekzu.org/avatar/"
article_num="5"
nick_name="逆旅"
blog_name="山中客"
domain ="https://www.gynl.xyz"
email_hash = "2c9a98ac69eb0258c13f3a1a88152d38"  #邮箱MD5值，自动填写
register="false"
github="https://www.github.com"
zhihu="https://www.zhihu.com"
telegram=""
email="779505388@qq.com"
    