[package]
edition = "2021"
name = "rblog"
version = "0.1.0"

[dependencies]
autocfg = "1.1.0"
libc = "0.2.125"
rand = "0.8.5"
rocket = "0.5.0-rc.1"
yansi = "0.5.1"



[dependencies.rocket_dyn_templates]
features = ["tera", "handlebars"]
default-features = false
